# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 06:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_celerytest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytest',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 6, 42, 27, 817740, tzinfo=utc)),
        ),
    ]
