# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='성과 이름을 붙여 적으세요', max_length=60),
        ),
    ]
