# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20170209_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='담당 강사'),
        ),
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1, verbose_name='셔츠 사이즈'),
        ),
    ]
