# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20170209_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.Person', verbose_name='사장님'),
        ),
    ]
