# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_auto_20170209_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
