# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_auto_20170209_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='follower_set', to='person.User'),
        ),
    ]
