# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170209_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pingbakcs_count',
            new_name='pingbacks_count',
        ),
    ]
