# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_myuser_bookmark_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bookmark_videos',
            field=models.ManyToManyField(blank=True, to='video.Video'),
        ),
    ]
