# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_bookmarkvideos_created_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookmarkvideos',
            table='asdfasdfasdf',
        ),
    ]
