# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20170223_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkvideos',
            old_name='myuser',
            new_name='user',
        ),
    ]
