# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20170223_0310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkVideos',
            new_name='BookmarkVideo',
        ),
    ]
