# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_url_thumbnail'),
        ('member', '0010_auto_20170223_0319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarkvideo',
            unique_together=set([('user', 'video')]),
        ),
    ]
